services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - gamer_club_db:/app/data
    env_file:
      - .env
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  gamer_club_db:
